// frontend/src/components/skeleton/AlbumCardSkeleton.tsx
import React from 'react';

export function AlbumCardSkeleton() {
  return (
    <div className="bg-punk-gray overflow-hidden animate-pulse">
      {/* Cover Image */}
      <div className="aspect-square bg-punk-black" />

      {/* Content */}
      <div className="p-4 space-y-3">
        {/* Title */}
        <div className="h-5 bg-punk-black w-3/4" />

        {/* Artist */}
        <div className="h-4 bg-punk-black w-1/2" />

        {/* Price */}
        <div className="h-6 bg-punk-black w-1/3" />

        {/* Add to Cart Button */}
        <div className="h-10 bg-punk-black" />
      </div>
    </div>
  );
}

interface AlbumCardSkeletonGridProps {
  count?: number;
}

export function AlbumCardSkeletonGrid({ count = 8 }: AlbumCardSkeletonGridProps) {
  return (
    <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-6">
      {[...Array(count)].map((_, i) => (
        <AlbumCardSkeleton key={i} />
      ))}
    </div>
  );
}

// frontendvue/src/components/skeleton/AlbumCardSkeleton.vue
<script setup lang="ts">
interface Props {
  count?: number
}

const props = withDefaults(defineProps<Props>(), {
  count: 1,
})
</script>

<template>
  <div
    v-for="n in props.count"
    :key="n"
    class="card-punk rounded-lg overflow-hidden"
  >
    <!-- Image skeleton -->
    <div class="aspect-square skeleton bg-punk-black" />

    <!-- Content skeleton -->
    <div class="p-4 space-y-3">
      <!-- Title -->
      <div class="skeleton h-5 w-3/4 bg-punk-black rounded" />

      <!-- Artist -->
      <div class="skeleton h-4 w-1/2 bg-punk-black rounded" />

      <!-- Price row -->
      <div class="flex items-center justify-between pt-2">
        <div class="skeleton h-6 w-20 bg-punk-black rounded" />
        <div class="skeleton h-8 w-8 bg-punk-black rounded-full" />
      </div>
    </div>
  </div>
</template>
