// frontend/src/components/product/AlbumFilters.tsx
import { useState, Fragment } from 'react';
import { Dialog, Transition } from '@headlessui/react';
import { X, SlidersHorizontal } from 'lucide-react';
import type { Genre } from '@/api/types';
import { AlbumFormat } from '@/api/types';
import { Button } from '@/components/common/Button';

export interface FilterState {
  formats: AlbumFormat[];
  genres: string[];
  priceRange: [number, number];
  sortBy: 'price' | 'release_year' | 'rating' | 'title';
  sortOrder: 'asc' | 'desc';
}

interface AlbumFiltersProps {
  filters: FilterState;
  onFilterChange: (filters: FilterState) => void;
  genres: Genre[];
}

export function AlbumFilters({ filters, onFilterChange, genres }: AlbumFiltersProps) {
  const [isOpen, setIsOpen] = useState(false);

  const handleFormatToggle = (format: AlbumFormat) => {
    const newFormats = filters.formats.includes(format)
      ? filters.formats.filter((f) => f !== format)
      : [...filters.formats, format];

    onFilterChange({ ...filters, formats: newFormats });
  };

  const handleGenreToggle = (genreUuid: string) => {
    const newGenres = filters.genres.includes(genreUuid)
      ? filters.genres.filter((g) => g !== genreUuid)
      : [...filters.genres, genreUuid];

    onFilterChange({ ...filters, genres: newGenres });
  };

  const handlePriceRangeChange = (index: 0 | 1, value: number) => {
    const newRange: [number, number] = [...filters.priceRange];
    newRange[index] = value;
    onFilterChange({ ...filters, priceRange: newRange });
  };

  const handleSortChange = (sortBy: FilterState['sortBy']) => {
    onFilterChange({ ...filters, sortBy });
  };

  const handleClearFilters = () => {
    onFilterChange({
      formats: [],
      genres: [],
      priceRange: [0, 100],
      sortBy: 'title',
      sortOrder: 'asc',
    });
  };

  const hasActiveFilters =
    filters.formats.length > 0 ||
    filters.genres.length > 0 ||
    filters.priceRange[0] > 0 ||
    filters.priceRange[1] < 100;

  const FilterContent = () => (
    <div className="space-y-6">
      {/* Sort By */}
      <div>
        <h3 className="font-bold text-white uppercase tracking-wider mb-3 text-sm">
          Sort By
        </h3>
        <div className="space-y-2">
          {[
            { value: 'title', label: 'Title (A-Z)' },
            { value: 'price', label: 'Price' },
            { value: 'release_year', label: 'Release Year' },
            { value: 'rating', label: 'Rating' },
          ].map((option) => (
            <label
              key={option.value}
              className="flex items-center gap-2 cursor-pointer group"
            >
              <input
                type="radio"
                name="sortBy"
                value={option.value}
                checked={filters.sortBy === option.value}
                onChange={() => handleSortChange(option.value as FilterState['sortBy'])}
                className="text-punk-orange focus:ring-punk-orange bg-punk-black border-punk-gray"
              />
              <span className="text-sm text-gray-400 group-hover:text-punk-orange transition-colors">
                {option.label}
              </span>
            </label>
          ))}
        </div>
      </div>

      {/* Format Filter */}
      <div>
        <h3 className="font-bold text-white uppercase tracking-wider mb-3 text-sm">
          Format
        </h3>
        <div className="space-y-2">
          {Object.values(AlbumFormat).map((format) => (
            <label
              key={format}
              className="flex items-center gap-2 cursor-pointer group"
            >
              <input
                type="checkbox"
                checked={filters.formats.includes(format)}
                onChange={() => handleFormatToggle(format)}
                className="rounded text-punk-orange focus:ring-punk-orange bg-punk-black border-punk-gray"
              />
              <span className="text-sm text-gray-400 group-hover:text-punk-orange transition-colors capitalize">
                {format}
              </span>
            </label>
          ))}
        </div>
      </div>

      {/* Genre Filter */}
      {genres.length > 0 && (
        <div>
          <h3 className="font-bold text-white uppercase tracking-wider mb-3 text-sm">
            Genres
          </h3>
          <div className="space-y-2 max-h-48 overflow-y-auto scrollbar-hide">
            {genres.map((genre) => (
              <label
                key={genre.uuid}
                className="flex items-center gap-2 cursor-pointer group"
              >
                <input
                  type="checkbox"
                  checked={filters.genres.includes(genre.uuid)}
                  onChange={() => handleGenreToggle(genre.uuid)}
                  className="rounded text-punk-orange focus:ring-punk-orange bg-punk-black border-punk-gray"
                />
                <span className="text-sm text-gray-400 group-hover:text-punk-orange transition-colors">
                  {genre.name}
                  {genre.albums_count !== undefined && (
                    <span className="text-gray-600 ml-1">
                      ({genre.albums_count})
                    </span>
                  )}
                </span>
              </label>
            ))}
          </div>
        </div>
      )}

      {/* Price Range */}
      <div>
        <h3 className="font-bold text-white uppercase tracking-wider mb-3 text-sm">
          Price Range
        </h3>
        <div className="space-y-4">
          <div>
            <label className="block text-sm text-gray-400 mb-1">
              Min: <span className="text-punk-orange font-bold">${filters.priceRange[0]}</span>
            </label>
            <input
              type="range"
              min="0"
              max="100"
              step="5"
              value={filters.priceRange[0]}
              onChange={(e) => handlePriceRangeChange(0, Number(e.target.value))}
              className="w-full h-1 bg-punk-black rounded-lg appearance-none cursor-pointer accent-punk-orange"
            />
          </div>
          <div>
            <label className="block text-sm text-gray-400 mb-1">
              Max: <span className="text-punk-orange font-bold">${filters.priceRange[1]}</span>
            </label>
            <input
              type="range"
              min="0"
              max="100"
              step="5"
              value={filters.priceRange[1]}
              onChange={(e) => handlePriceRangeChange(1, Number(e.target.value))}
              className="w-full h-1 bg-punk-black rounded-lg appearance-none cursor-pointer accent-punk-orange"
            />
          </div>
        </div>
      </div>

      {/* Clear Filters */}
      {hasActiveFilters && (
        <Button
          onClick={handleClearFilters}
          variant="outline"
          size="sm"
          fullWidth
        >
          Clear Filters
        </Button>
      )}
    </div>
  );

  return (
    <>
      {/* Mobile Filter Button */}
      <div className="lg:hidden mb-4">
        <Button
          onClick={() => setIsOpen(true)}
          variant="outline"
          fullWidth
        >
          <SlidersHorizontal className="h-4 w-4 mr-2" />
          Filters
          {hasActiveFilters && (
            <span className="ml-2 px-2 py-0.5 bg-punk-orange text-white text-xs">
              Active
            </span>
          )}
        </Button>
      </div>

      {/* Desktop Sidebar */}
      <div className="hidden lg:block">
        <div className="bg-punk-gray p-6 sticky top-20">
          <div className="flex items-center justify-between mb-6">
            <h2 className="text-lg font-bold text-white uppercase tracking-wider">
              Filters
            </h2>
            {hasActiveFilters && (
              <span className="px-2 py-1 bg-punk-orange text-white text-xs font-bold">
                Active
              </span>
            )}
          </div>
          <FilterContent />
        </div>
      </div>

      {/* Mobile Filter Modal */}
      <Transition appear show={isOpen} as={Fragment}>
        <Dialog as="div" className="relative z-50 lg:hidden" onClose={() => setIsOpen(false)}>
          <Transition.Child
            as={Fragment}
            enter="ease-out duration-300"
            enterFrom="opacity-0"
            enterTo="opacity-100"
            leave="ease-in duration-200"
            leaveFrom="opacity-100"
            leaveTo="opacity-0"
          >
            <div className="fixed inset-0 bg-black bg-opacity-80" />
          </Transition.Child>

          <div className="fixed inset-0 overflow-hidden">
            <div className="absolute inset-0 overflow-hidden">
              <div className="pointer-events-none fixed inset-y-0 right-0 flex max-w-full pl-10">
                <Transition.Child
                  as={Fragment}
                  enter="transform transition ease-in-out duration-300"
                  enterFrom="translate-x-full"
                  enterTo="translate-x-0"
                  leave="transform transition ease-in-out duration-300"
                  leaveFrom="translate-x-0"
                  leaveTo="translate-x-full"
                >
                  <Dialog.Panel className="pointer-events-auto w-screen max-w-md">
                    <div className="flex h-full flex-col overflow-y-scroll bg-punk-gray shadow-xl">
                      <div className="flex items-center justify-between px-6 py-6 border-b border-punk-black">
                        <Dialog.Title className="text-xl font-bold text-white uppercase tracking-wider">
                          Filters
                        </Dialog.Title>
                        <button
                          onClick={() => setIsOpen(false)}
                          className="text-gray-400 hover:text-punk-orange transition-colors"
                        >
                          <X className="h-6 w-6" />
                        </button>
                      </div>
                      <div className="p-6">
                        <FilterContent />
                      </div>
                    </div>
                  </Dialog.Panel>
                </Transition.Child>
              </div>
            </div>
          </div>
        </Dialog>
      </Transition>
    </>
  );
}

// frontendvue/src/components/product/AlbumFilters.vue
<script setup lang="ts">
import { ref, computed, watch } from 'vue'
import {
  XMarkIcon,
  FunnelIcon,
  ChevronDownIcon,
} from '@heroicons/vue/24/outline'
import { AlbumFormat, type Genre } from '@/api/types/models'
import { ALBUM_FORMAT_LABELS } from '@/utils/constants'

interface Props {
  genres?: Genre[]
  modelValue: {
    genre?: string
    format?: string
    minPrice?: number
    maxPrice?: number
    sort?: string
  }
}

const props = withDefaults(defineProps<Props>(), {
  genres: () => [],
})

const emit = defineEmits<{
  (e: 'update:modelValue', value: Props['modelValue']): void
  (e: 'clear'): void
}>()

const isOpen = ref(false)
const localFilters = ref({ ...props.modelValue })

const sortOptions = [
  { value: '', label: 'Default' },
  { value: 'newest', label: 'Newest First' },
  { value: 'price_asc', label: 'Price: Low to High' },
  { value: 'price_desc', label: 'Price: High to Low' },
  { value: 'title', label: 'Title A-Z' },
  { value: 'rating', label: 'Highest Rated' },
]

const formatOptions = Object.entries(ALBUM_FORMAT_LABELS).map(([value, label]) => ({
  value,
  label,
}))

const activeFiltersCount = computed(() => {
  let count = 0
  if (localFilters.value.genre) count++
  if (localFilters.value.format) count++
  if (localFilters.value.minPrice) count++
  if (localFilters.value.maxPrice) count++
  if (localFilters.value.sort) count++
  return count
})

watch(
  () => props.modelValue,
  (newVal) => {
    localFilters.value = { ...newVal }
  },
  { deep: true }
)

const applyFilters = () => {
  emit('update:modelValue', { ...localFilters.value })
  isOpen.value = false
}

const clearFilters = () => {
  localFilters.value = {}
  emit('update:modelValue', {})
  emit('clear')
}

const toggleMobileFilters = () => {
  isOpen.value = !isOpen.value
}
</script>

<template>
  <div>
    <!-- Mobile filter button -->
    <button
      type="button"
      class="lg:hidden flex items-center gap-2 px-4 py-2 bg-punk-gray rounded-lg text-white hover:bg-punk-black transition-colors"
      @click="toggleMobileFilters"
    >
      <FunnelIcon class="h-5 w-5" />
      Filters
      <span
        v-if="activeFiltersCount > 0"
        class="ml-1 px-2 py-0.5 bg-punk-orange rounded-full text-xs"
      >
        {{ activeFiltersCount }}
      </span>
    </button>

    <!-- Mobile filter drawer -->
    <Teleport to="body">
      <Transition
        enter-active-class="transition-opacity duration-200"
        enter-from-class="opacity-0"
        enter-to-class="opacity-100"
        leave-active-class="transition-opacity duration-200"
        leave-from-class="opacity-100"
        leave-to-class="opacity-0"
      >
        <div
          v-if="isOpen"
          class="lg:hidden fixed inset-0 z-50 bg-black/70"
          @click="isOpen = false"
        />
      </Transition>

      <Transition
        enter-active-class="transition-transform duration-300"
        enter-from-class="translate-x-full"
        enter-to-class="translate-x-0"
        leave-active-class="transition-transform duration-300"
        leave-from-class="translate-x-0"
        leave-to-class="translate-x-full"
      >
        <div
          v-if="isOpen"
          class="lg:hidden fixed right-0 top-0 bottom-0 w-80 max-w-full bg-punk-dark z-50 overflow-y-auto"
        >
          <div class="p-4">
            <div class="flex items-center justify-between mb-6">
              <h2 class="text-lg font-semibold text-white">Filters</h2>
              <button
                type="button"
                class="text-gray-400 hover:text-white"
                @click="isOpen = false"
              >
                <XMarkIcon class="h-6 w-6" />
              </button>
            </div>

            <!-- Filter content (shared) -->
            <div class="space-y-6">
              <slot name="filters" :filters="localFilters" />
            </div>

            <!-- Mobile apply buttons -->
            <div class="mt-6 flex gap-3">
              <button
                type="button"
                class="flex-1 btn-punk-outline text-sm"
                @click="clearFilters"
              >
                Clear All
              </button>
              <button
                type="button"
                class="flex-1 btn-punk text-sm"
                @click="applyFilters"
              >
                Apply
              </button>
            </div>
          </div>
        </div>
      </Transition>
    </Teleport>

    <!-- Desktop sidebar filters -->
    <div class="hidden lg:block space-y-6">
      <!-- Sort -->
      <div>
        <label class="block text-sm font-medium text-gray-300 mb-2">Sort By</label>
        <select
          v-model="localFilters.sort"
          class="w-full bg-punk-black border border-punk-gray rounded-lg px-3 py-2 text-white focus:border-punk-orange focus:ring-1 focus:ring-punk-orange"
          @change="applyFilters"
        >
          <option
            v-for="option in sortOptions"
            :key="option.value"
            :value="option.value"
          >
            {{ option.label }}
          </option>
        </select>
      </div>

      <!-- Genre -->
      <div v-if="props.genres.length > 0">
        <label class="block text-sm font-medium text-gray-300 mb-2">Genre</label>
        <select
          v-model="localFilters.genre"
          class="w-full bg-punk-black border border-punk-gray rounded-lg px-3 py-2 text-white focus:border-punk-orange focus:ring-1 focus:ring-punk-orange"
          @change="applyFilters"
        >
          <option value="">All Genres</option>
          <option
            v-for="genre in props.genres"
            :key="genre.slug"
            :value="genre.slug"
          >
            {{ genre.name }}
          </option>
        </select>
      </div>

      <!-- Format -->
      <div>
        <label class="block text-sm font-medium text-gray-300 mb-2">Format</label>
        <select
          v-model="localFilters.format"
          class="w-full bg-punk-black border border-punk-gray rounded-lg px-3 py-2 text-white focus:border-punk-orange focus:ring-1 focus:ring-punk-orange"
          @change="applyFilters"
        >
          <option value="">All Formats</option>
          <option
            v-for="format in formatOptions"
            :key="format.value"
            :value="format.value"
          >
            {{ format.label }}
          </option>
        </select>
      </div>

      <!-- Price Range -->
      <div>
        <label class="block text-sm font-medium text-gray-300 mb-2">Price Range</label>
        <div class="flex items-center gap-2">
          <input
            v-model.number="localFilters.minPrice"
            type="number"
            min="0"
            placeholder="Min"
            class="w-full bg-punk-black border border-punk-gray rounded-lg px-3 py-2 text-white focus:border-punk-orange focus:ring-1 focus:ring-punk-orange"
            @change="applyFilters"
          />
          <span class="text-gray-500">-</span>
          <input
            v-model.number="localFilters.maxPrice"
            type="number"
            min="0"
            placeholder="Max"
            class="w-full bg-punk-black border border-punk-gray rounded-lg px-3 py-2 text-white focus:border-punk-orange focus:ring-1 focus:ring-punk-orange"
            @change="applyFilters"
          />
        </div>
      </div>

      <!-- Clear filters -->
      <button
        v-if="activeFiltersCount > 0"
        type="button"
        class="w-full text-sm text-punk-orange hover:text-punk-coral transition-colors"
        @click="clearFilters"
      >
        Clear all filters ({{ activeFiltersCount }})
      </button>
    </div>
  </div>
</template>
