// frontendvue/src/components/product/AlbumGrid.vue
<template>
  <div>
    <!-- Loading State -->
    <div v-if="loading" class="grid grid-cols-1 gap-6 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">
      <div v-for="i in 8" :key="i" class="animate-pulse">
        <div class="aspect-square bg-punk-gray rounded-lg" />
        <div class="mt-4 space-y-2">
          <div class="h-4 bg-punk-gray rounded w-3/4" />
          <div class="h-3 bg-punk-gray rounded w-1/2" />
          <div class="h-4 bg-punk-gray rounded w-1/4" />
        </div>
      </div>
    </div>

    <!-- Empty State -->
    <div v-else-if="!albums || albums.length === 0" class="text-center py-20">
      <div class="w-20 h-20 mx-auto mb-6 rounded-full bg-punk-gray flex items-center justify-center">
        <MusicalNoteIcon class="h-10 w-10 text-gray-500" />
      </div>
      <h3 class="text-xl font-display font-bold text-white uppercase tracking-wider">
        No albums found
      </h3>
      <p class="mt-2 text-gray-400">Try adjusting your filters or search criteria</p>
    </div>

    <!-- Albums Grid -->
    <div v-else class="grid grid-cols-1 gap-6 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">
      <AlbumCard v-for="album in albums" :key="album.uuid" :album="album" />
    </div>

    <!-- Pagination -->
    <div v-if="pagination && pagination.last_page > 1" class="mt-8 flex justify-center">
      <nav class="flex items-center gap-2">
        <button
          @click="$emit('page-change', pagination.current_page - 1)"
          :disabled="pagination.current_page === 1"
          class="px-4 py-2 rounded-lg bg-punk-gray border border-gray-700 text-sm font-medium text-gray-400 hover:text-white hover:border-punk-orange transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
        >
          <ChevronLeftIcon class="h-5 w-5" />
        </button>

        <div class="flex items-center gap-1">
          <button
            v-for="page in visiblePages"
            :key="page"
            @click="$emit('page-change', page)"
            :class="[
              'px-4 py-2 rounded-lg text-sm font-medium transition-colors',
              page === pagination.current_page
                ? 'bg-punk-orange text-white'
                : 'bg-punk-gray border border-gray-700 text-gray-400 hover:text-white hover:border-punk-orange'
            ]"
          >
            {{ page }}
          </button>
        </div>

        <button
          @click="$emit('page-change', pagination.current_page + 1)"
          :disabled="pagination.current_page === pagination.last_page"
          class="px-4 py-2 rounded-lg bg-punk-gray border border-gray-700 text-sm font-medium text-gray-400 hover:text-white hover:border-punk-orange transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
        >
          <ChevronRightIcon class="h-5 w-5" />
        </button>
      </nav>
    </div>

    <!-- Page Info -->
    <div v-if="pagination" class="mt-4 text-center text-sm text-gray-500">
      Showing {{ pagination.from || 0 }} - {{ pagination.to || 0 }} of {{ pagination.total || 0 }} albums
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue'
import { MusicalNoteIcon, ChevronLeftIcon, ChevronRightIcon } from '@heroicons/vue/24/outline'
import type { Album, PaginationMeta } from '@/api/types/models'
import AlbumCard from './AlbumCard.vue'

interface Props {
  albums?: Album[]
  pagination?: PaginationMeta
  loading?: boolean
}

const props = defineProps<Props>()

defineEmits<{
  'page-change': [page: number]
}>()

const visiblePages = computed(() => {
  if (!props.pagination) return []

  const current = props.pagination.current_page
  const last = props.pagination.last_page
  const delta = 2
  const pages: number[] = []

  for (let i = Math.max(1, current - delta); i <= Math.min(last, current + delta); i++) {
    pages.push(i)
  }

  return pages
})
</script>

// frontend/src/components/product/AlbumGrid.tsx
import React from 'react';
import type { Album } from '@/api/types';
import { AlbumCard } from './AlbumCard';

interface AlbumGridProps {
  albums: Album[];
  isLoading?: boolean;
}

export function AlbumGrid({ albums, isLoading = false }: AlbumGridProps) {
  if (isLoading) {
    return (
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-6">
        {[...Array(8)].map((_, index) => (
          <AlbumCardSkeleton key={index} />
        ))}
      </div>
    );
  }

  if (albums.length === 0) {
    return (
      <div className="text-center py-12">
        <svg
          className="mx-auto h-24 w-24 text-gray-400 dark:text-gray-500 mb-4"
          fill="none"
          viewBox="0 0 24 24"
          stroke="currentColor"
        >
          <path
            strokeLinecap="round"
            strokeLinejoin="round"
            strokeWidth={1.5}
            d="M9 19V6l12-3v13M9 19c0 1.105-1.343 2-3 2s-3-.895-3-2 1.343-2 3-2 3 .895 3 2zm12-3c0 1.105-1.343 2-3 2s-3-.895-3-2 1.343-2 3-2 3 .895 3 2zM9 10l12-3"
          />
        </svg>
        <h3 className="text-lg font-medium text-gray-900 dark:text-gray-100 mb-2">
          No albums found
        </h3>
        <p className="text-gray-600 dark:text-gray-400">
          Try adjusting your filters or search criteria
        </p>
      </div>
    );
  }

  return (
    <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-6">
      {albums.map((album) => (
        <AlbumCard key={album.uuid} album={album} />
      ))}
    </div>
  );
}

function AlbumCardSkeleton() {
  return (
    <div className="bg-white dark:bg-gray-800 rounded-lg shadow-md overflow-hidden animate-pulse">
      {/* Image skeleton */}
      <div className="aspect-square bg-gray-200 dark:bg-gray-700" />

      {/* Content skeleton */}
      <div className="p-4 space-y-3">
        {/* Format badge */}
        <div className="h-5 w-16 bg-gray-200 dark:bg-gray-700 rounded-full" />

        {/* Title */}
        <div className="h-6 bg-gray-200 dark:bg-gray-700 rounded w-3/4" />

        {/* Artist */}
        <div className="h-4 bg-gray-200 dark:bg-gray-700 rounded w-1/2" />

        {/* Rating */}
        <div className="flex items-center gap-2">
          <div className="h-5 w-24 bg-gray-200 dark:bg-gray-700 rounded" />
          <div className="h-4 w-8 bg-gray-200 dark:bg-gray-700 rounded" />
        </div>

        {/* Price */}
        <div className="h-7 bg-gray-200 dark:bg-gray-700 rounded w-1/3" />

        {/* Button */}
        <div className="h-10 bg-gray-200 dark:bg-gray-700 rounded" />
      </div>
    </div>
  );
}
