// frontendvue/src/components/product/ReviewForm.vue
<script setup lang="ts">
import { ref, computed } from 'vue'
import { StarIcon } from '@heroicons/vue/24/solid'
import { StarIcon as StarOutlineIcon } from '@heroicons/vue/24/outline'
import { useToast } from 'vue-toastification'
import { reviewsApi } from '@/api/endpoints/reviews'

interface Props {
  albumSlug: string
  existingReview?: {
    rating: number
    title?: string
    body?: string
  }
}

const props = defineProps<Props>()

const emit = defineEmits<{
  (e: 'submitted'): void
  (e: 'cancelled'): void
}>()

const toast = useToast()
const isSubmitting = ref(false)
const rating = ref(props.existingReview?.rating ?? 0)
const title = ref(props.existingReview?.title ?? '')
const body = ref(props.existingReview?.body ?? '')
const hoverRating = ref(0)

const isEditing = computed(() => !!props.existingReview)
const bodyLength = computed(() => body.value.length)
const maxBodyLength = 2000

const setRating = (value: number) => {
  rating.value = value
}

const handleSubmit = async () => {
  if (rating.value === 0) {
    toast.error('Please select a rating')
    return
  }

  if (body.value.length > 0 && body.value.length < 10) {
    toast.error('Review must be at least 10 characters')
    return
  }

  isSubmitting.value = true

  try {
    const input = {
      rating: rating.value,
      title: title.value || undefined,
      body: body.value || undefined,
    }

    if (isEditing.value) {
      await reviewsApi.updateReview(props.albumSlug, input)
      toast.success('Review updated successfully')
    } else {
      await reviewsApi.createReview(props.albumSlug, input)
      toast.success('Review submitted successfully')
    }

    emit('submitted')
  } catch (error: any) {
    const message = error?.response?.data?.message || 'Failed to submit review'
    toast.error(message)
  } finally {
    isSubmitting.value = false
  }
}

const handleCancel = () => {
  emit('cancelled')
}
</script>

<template>
  <form class="space-y-4" @submit.prevent="handleSubmit">
    <!-- Rating -->
    <div>
      <label class="block text-sm font-medium text-gray-300 mb-2">
        Rating <span class="text-red-500">*</span>
      </label>
      <div class="flex gap-1">
        <button
          v-for="star in 5"
          :key="star"
          type="button"
          class="focus:outline-none transition-transform hover:scale-110"
          @click="setRating(star)"
          @mouseenter="hoverRating = star"
          @mouseleave="hoverRating = 0"
        >
          <StarIcon
            v-if="star <= (hoverRating || rating)"
            class="h-8 w-8 text-punk-orange"
          />
          <StarOutlineIcon
            v-else
            class="h-8 w-8 text-gray-500"
          />
        </button>
      </div>
    </div>

    <!-- Title (optional) -->
    <div>
      <label class="block text-sm font-medium text-gray-300 mb-2">
        Title (optional)
      </label>
      <input
        v-model="title"
        type="text"
        maxlength="255"
        placeholder="Summarize your review"
        class="w-full bg-punk-black border border-punk-gray rounded-lg px-4 py-2 text-white placeholder-gray-500 focus:border-punk-orange focus:ring-1 focus:ring-punk-orange"
      />
    </div>

    <!-- Body (optional) -->
    <div>
      <label class="block text-sm font-medium text-gray-300 mb-2">
        Review (optional)
      </label>
      <textarea
        v-model="body"
        rows="4"
        :maxlength="maxBodyLength"
        placeholder="Share your thoughts about this album..."
        class="w-full bg-punk-black border border-punk-gray rounded-lg px-4 py-2 text-white placeholder-gray-500 focus:border-punk-orange focus:ring-1 focus:ring-punk-orange resize-none"
      />
      <div class="mt-1 text-right text-xs text-gray-500">
        {{ bodyLength }} / {{ maxBodyLength }}
      </div>
    </div>

    <!-- Buttons -->
    <div class="flex gap-3 pt-2">
      <button
        type="button"
        class="btn-punk-outline flex-1"
        :disabled="isSubmitting"
        @click="handleCancel"
      >
        Cancel
      </button>
      <button
        type="submit"
        class="btn-punk flex-1"
        :disabled="isSubmitting || rating === 0"
      >
        {{ isSubmitting ? 'Submitting...' : isEditing ? 'Update Review' : 'Submit Review' }}
      </button>
    </div>
  </form>
</template>

// frontend/src/components/product/ReviewForm.tsx
import React, { useState } from 'react';
import { useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import { reviewSchema, type ReviewFormData } from '@/utils/validators';
import { Input } from '@/components/common/Input';
import { Button } from '@/components/common/Button';
import { RatingStars } from './RatingStars';
import { useCreateReview, useUpdateReview } from '@/hooks/api/useReviews';
import toast from 'react-hot-toast';

interface ReviewFormProps {
  albumSlug: string;
  onSuccess?: () => void;
}

export function ReviewForm({ albumSlug, onSuccess }: ReviewFormProps) {
  const [rating, setRating] = useState(0);
  const [isSubmitting, setIsSubmitting] = useState(false);

  const createReview = useCreateReview();
  const updateReview = useUpdateReview();

  const {
    register,
    handleSubmit,
    formState: { errors },
    setValue,
    reset,
  } = useForm<ReviewFormData>({
    resolver: zodResolver(reviewSchema),
    defaultValues: {
      rating: 0,
      title: '',
      body: '',
    },
  });

  const handleRatingChange = (newRating: number) => {
    setRating(newRating);
    setValue('rating', newRating, { shouldValidate: true });
  };

  const onSubmit = async (data: ReviewFormData) => {
    try {
      setIsSubmitting(true);

      await createReview.mutateAsync({
        albumSlug,
        data: {
          rating: data.rating,
          title: data.title,
          body: data.body,
        },
      });

      toast.success('Review submitted successfully!');

      // Reset form
      reset();
      setRating(0);

      // Call success callback
      onSuccess?.();
    } catch (error: any) {
      const errorMessage = error.message || 'Failed to submit review';
      toast.error(errorMessage);
    } finally {
      setIsSubmitting(false);
    }
  };

  return (
    <div className="bg-white dark:bg-gray-800 rounded-lg p-6 shadow-sm border border-gray-200 dark:border-gray-700">
      <h3 className="text-xl font-bold text-gray-900 dark:text-gray-100 mb-6">
        Write a Review
      </h3>

      <form onSubmit={handleSubmit(onSubmit)} className="space-y-6">
        {/* Rating Input */}
        <div>
          <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
            Rating <span className="text-red-500">*</span>
          </label>
          <div className="flex items-center gap-4">
            <RatingStars
              value={rating}
              onChange={handleRatingChange}
              size="lg"
            />
            {rating > 0 && (
              <span className="text-sm text-gray-600 dark:text-gray-400">
                {rating} {rating === 1 ? 'star' : 'stars'}
              </span>
            )}
          </div>
          {errors.rating && (
            <p className="mt-1 text-sm text-red-600 dark:text-red-400">
              {errors.rating.message}
            </p>
          )}
        </div>

        {/* Title Input */}
        <div>
          <label
            htmlFor="review-title"
            className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1"
          >
            Review Title (Optional)
          </label>
          <input
            id="review-title"
            type="text"
            {...register('title')}
            placeholder="Summarize your review in a few words"
            className="block w-full px-3 py-2 border rounded-lg shadow-sm text-gray-900 dark:text-gray-100 bg-white dark:bg-gray-800 placeholder-gray-400 dark:placeholder-gray-500 focus:outline-none focus:ring-2 focus:ring-primary-500 focus:border-transparent transition-colors border-gray-300 dark:border-gray-600"
          />
          {errors.title && (
            <p className="mt-1 text-sm text-red-600 dark:text-red-400">
              {errors.title.message}
            </p>
          )}
        </div>

        {/* Review Body */}
        <div>
          <label
            htmlFor="review-body"
            className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1"
          >
            Your Review (Optional)
          </label>
          <textarea
            id="review-body"
            {...register('body')}
            rows={5}
            placeholder="Share your thoughts about this album..."
            className="block w-full px-3 py-2 border rounded-lg shadow-sm text-gray-900 dark:text-gray-100 bg-white dark:bg-gray-800 placeholder-gray-400 dark:placeholder-gray-500 focus:outline-none focus:ring-2 focus:ring-primary-500 focus:border-transparent transition-colors border-gray-300 dark:border-gray-600 resize-none"
          />
          {errors.body && (
            <p className="mt-1 text-sm text-red-600 dark:text-red-400">
              {errors.body.message}
            </p>
          )}
          <p className="mt-1 text-xs text-gray-500 dark:text-gray-400">
            Minimum 10 characters, maximum 2000 characters
          </p>
        </div>

        {/* Submit Button */}
        <div className="flex items-center gap-4">
          <Button
            type="submit"
            variant="primary"
            size="md"
            isLoading={isSubmitting}
            disabled={isSubmitting}
          >
            {isSubmitting ? 'Submitting...' : 'Submit Review'}
          </Button>
          <Button
            type="button"
            variant="ghost"
            size="md"
            onClick={() => {
              reset();
              setRating(0);
            }}
            disabled={isSubmitting}
          >
            Cancel
          </Button>
        </div>
      </form>
    </div>
  );
}
