// frontend/src/components/common/Breadcrumb.tsx
import { Link } from 'react-router-dom';
import { ChevronRight, Home } from 'lucide-react';

export interface BreadcrumbItem {
  label: string;
  href?: string;
}

interface BreadcrumbProps {
  items: BreadcrumbItem[];
  showHome?: boolean;
}

export function Breadcrumb({ items, showHome = true }: BreadcrumbProps) {
  const allItems: BreadcrumbItem[] = showHome
    ? [{ label: 'Home', href: '/' }, ...items]
    : items;

  return (
    <nav aria-label="Breadcrumb" className="mb-6">
      <ol className="flex items-center flex-wrap gap-1 text-sm">
        {allItems.map((item, index) => {
          const isLast = index === allItems.length - 1;
          const isHome = index === 0 && showHome;

          return (
            <li key={index} className="flex items-center">
              {index > 0 && (
                <ChevronRight className="h-4 w-4 mx-1 text-gray-400 dark:text-gray-500 flex-shrink-0" />
              )}

              {isLast ? (
                <span className="text-gray-900 dark:text-gray-100 font-medium truncate max-w-[200px]">
                  {item.label}
                </span>
              ) : item.href ? (
                <Link
                  to={item.href}
                  className="text-gray-600 dark:text-gray-400 hover:text-primary-600 dark:hover:text-primary-400 transition-colors flex items-center gap-1"
                >
                  {isHome && <Home className="h-4 w-4" />}
                  <span className={isHome ? 'sr-only sm:not-sr-only' : ''}>
                    {item.label}
                  </span>
                </Link>
              ) : (
                <span className="text-gray-600 dark:text-gray-400">
                  {item.label}
                </span>
              )}
            </li>
          );
        })}
      </ol>
    </nav>
  );
}

// frontendvue/src/components/common/Breadcrumb.vue
<script setup lang="ts">
import { ChevronRightIcon, HomeIcon } from '@heroicons/vue/24/outline'

interface BreadcrumbItem {
  label: string
  href?: string
}

interface Props {
  items: BreadcrumbItem[]
  showHome?: boolean
}

const props = withDefaults(defineProps<Props>(), {
  showHome: true,
})
</script>

<template>
  <nav class="flex" aria-label="Breadcrumb">
    <ol class="flex items-center space-x-2">
      <!-- Home link -->
      <li v-if="props.showHome">
        <router-link
          to="/"
          class="text-gray-400 hover:text-punk-orange transition-colors"
        >
          <HomeIcon class="h-5 w-5" />
          <span class="sr-only">Home</span>
        </router-link>
      </li>

      <!-- Breadcrumb items -->
      <li
        v-for="(item, index) in props.items"
        :key="index"
        class="flex items-center"
      >
        <ChevronRightIcon class="h-4 w-4 text-gray-500 mx-2" />

        <!-- Link or text based on whether it's the last item -->
        <router-link
          v-if="item.href && index !== props.items.length - 1"
          :to="item.href"
          class="text-gray-400 hover:text-punk-orange transition-colors text-sm"
        >
          {{ item.label }}
        </router-link>
        <span
          v-else
          class="text-gray-200 text-sm font-medium"
          :aria-current="index === props.items.length - 1 ? 'page' : undefined"
        >
          {{ item.label }}
        </span>
      </li>
    </ol>
  </nav>
</template>
